AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: API Gateway and Lambda integration for Yeojeong project

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod
    Description: Environment name
    
  ProjectName:
    Type: String
    Default: yeojeong
    Description: Project name

Resources:
  # API Gateway REST API
  YeojeongApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub '${ProjectName}-${Environment}-api'
      StageName: !Ref Environment
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"
      Auth:
        DefaultAuthorizer: NONE
      GatewayResponses:
        DEFAULT_4XX:
          ResponseParameters:
            Headers:
              Access-Control-Allow-Origin: "'*'"
        DEFAULT_5XX:
          ResponseParameters:
            Headers:
              Access-Control-Allow-Origin: "'*'"
      AccessLogSetting:
        DestinationArn: !GetAtt ApiLogGroup.Arn
        Format: '$context.requestId $context.extendedRequestId $context.identity.sourceIp $context.requestTime $context.routeKey $context.status'
      
  # CloudWatch Log Group for API Gateway
  ApiLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/apigateway/${ProjectName}-${Environment}'
      RetentionInDays: 30
      
  # Sample Lambda Function
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${ProjectName}-${Environment}-hello-world'
      CodeUri: ../../lambda/hello-world/
      Handler: index.handler
      Runtime: nodejs18.x
      MemorySize: 128
      Timeout: 30
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment
      Events:
        HelloWorldApi:
          Type: Api
          Properties:
            RestApiId: !Ref YeojeongApi
            Path: /hello
            Method: GET
      Tags:
        Environment: !Ref Environment
        Project: !Ref ProjectName
        
  # Lambda Function Log Group
  HelloWorldLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${ProjectName}-${Environment}-hello-world'
      RetentionInDays: 30

Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub 'https://${YeojeongApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}'
    Export:
      Name: !Sub '${ProjectName}-${Environment}-api-url'
      
  ApiId:
    Description: API Gateway ID
    Value: !Ref YeojeongApi
    Export:
      Name: !Sub '${ProjectName}-${Environment}-api-id'
      
  HelloWorldFunctionArn:
    Description: Hello World Lambda Function ARN
    Value: !GetAtt HelloWorldFunction.Arn
    Export:
      Name: !Sub '${ProjectName}-${Environment}-hello-world-arn'
